# Example configuration file for Airtable WhatsApp Agent
# Copy this file to config.yaml and update with your actual values

# Application environment (development, staging, production, testing)
environment: development
debug: true
testing: false
timezone: UTC

# Database configuration
database:
  url: "postgresql://user:password@localhost:5432/airtable_whatsapp"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo: false

# Redis configuration for caching and rate limiting
redis:
  url: "redis://localhost:6379/0"
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

# WhatsApp Business API configuration
whatsapp:
  access_token: "YOUR_WHATSAPP_ACCESS_TOKEN"
  phone_number_id: "YOUR_PHONE_NUMBER_ID"
  business_account_id: "YOUR_BUSINESS_ACCOUNT_ID"
  webhook_verify_token: "YOUR_WEBHOOK_VERIFY_TOKEN"
  api_version: "v18.0"
  base_url: "https://graph.facebook.com"
  timeout: 30
  max_retries: 3
  retry_delay: 1.0
  rate_limit_requests: 1000
  rate_limit_window: 3600

# Airtable API configuration
airtable:
  api_key: "YOUR_AIRTABLE_API_KEY"
  base_id: "YOUR_AIRTABLE_BASE_ID"
  table_name: "YOUR_TABLE_NAME"
  timeout: 30
  max_retries: 3
  retry_delay: 1.0
  rate_limit_requests: 5
  rate_limit_window: 1

# MCP (Model Context Protocol) server configuration
mcp:
  airtable_server_url: "http://airtable-mcp:8000"
  whatsapp_server_url: "http://whatsapp-mcp:8001"
  timeout: 30
  max_retries: 3
  retry_delay: 1.0

# Security configuration
security:
  cors_origins:
    - "*"
  allowed_hosts:
    - "*"

# Monitoring and observability
monitoring:
  enable_metrics: true
  metrics_port: 9090
  health_check_interval: 60
  log_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: null  # Set to a file path to enable file logging
  max_log_file_size: 10485760  # 10MB
  log_backup_count: 5
  enable_tracing: false
  jaeger_endpoint: null

# Server configuration
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  worker_class: "uvicorn.workers.UvicornWorker"
  max_requests: 1000
  max_requests_jitter: 100
  timeout: 30
  keepalive: 2
  reload: true  # Set to false in production
  debug: true   # Set to false in production

# Additional settings
max_file_size: 10485760  # 10MB
temp_dir: "/tmp"
data_dir: "./data"