"""
Utility modules for the Airtable WhatsApp Agent.

This package provides common utilities including error handling, rate limiting,
monitoring, configuration management, and other shared functionality.
"""

from .error_handling import (
    ErrorHandler,
    ErrorSeverity,
    RetryStrategy,
    RetryConfig,
    CircuitBreakerConfig,
    CircuitBreaker,
    error_handler,
    retry_on_failure,
    circuit_breaker,
    AIRTABLE_RETRY_CONFIG,
    WHATSAPP_RETRY_CONFIG,
    OPENAI_RETRY_CONFIG,
    EXTERNAL_MCP_RETRY_CONFIG
)

from .rate_limiter import (
    RateLimiter,
    RateLimitStrategy,
    RateLimitScope,
    RateLimitConfig,
    RateLimitResult,
    RateLimitMiddleware,
    TokenBucket,
    SlidingWindowCounter,
    AdaptiveRateLimiter,
    WHATSAPP_RATE_LIMIT,
    AIRTABLE_RATE_LIMIT,
    OPENAI_RATE_LIMIT,
    EXTERNAL_MCP_RATE_LIMIT
)

from .monitoring import (
    HealthChecker,
    MetricsCollector,
    HealthStatus,
    ComponentType,
    HealthCheckResult,
    SystemMetrics,
    health_checker,
    metrics_collector,
    setup_default_health_checks,
    check_whatsapp_api,
    check_airtable_api,
    check_database_connection,
    check_redis_connection,
)

from .config_manager import (
    ConfigManager,
    AppConfig,
    DatabaseConfig,
    RedisConfig,
    WhatsAppConfig,
    AirtableConfig,
    SecurityConfig,
    MonitoringConfig,
    ServerConfig,
    Environment,
    LogLevel,
    config_manager,
    get_config,
    load_config,
)

from .logging import (
    LogLevel as LoggingLevel,
    StructuredFormatter,
    ColoredFormatter,
    LoggerManager,
    logger_manager,
    get_logger,
    configure_logging,
    log_function_call,
    log_function_result,
    log_api_request,
    log_api_response,
)

from .validation import (
    ValidationError,
    ValidationSeverity,
    ValidationResult,
    Validator,
    StringValidator,
    EmailValidator,
    PhoneValidator,
    URLValidator,
    NumberValidator,
    ListValidator,
    DictValidator,
    JSONValidator,
    DateTimeValidator,
    validate_email,
    validate_phone,
    validate_url,
    validate_json,
    sanitize_string,
    sanitize_phone,
    validate_whatsapp_number,
    validate_airtable_record_id,
    validate_airtable_base_id,
)

__all__ = [
    # Error handling
    "ErrorHandler",
    "ErrorSeverity",
    "RetryStrategy",
    "RetryConfig",
    "CircuitBreakerConfig",
    "CircuitBreaker",
    "error_handler",
    "retry_on_failure",
    "circuit_breaker",
    "AIRTABLE_RETRY_CONFIG",
    "WHATSAPP_RETRY_CONFIG",
    "OPENAI_RETRY_CONFIG",
    "EXTERNAL_MCP_RETRY_CONFIG",
    
    # Rate limiting
    "RateLimiter",
    "RateLimitStrategy",
    "RateLimitScope",
    "RateLimitConfig",
    "RateLimitResult",
    "RateLimitMiddleware",
    "TokenBucket",
    "SlidingWindowCounter",
    "AdaptiveRateLimiter",
    "WHATSAPP_RATE_LIMIT",
    "AIRTABLE_RATE_LIMIT",
    "OPENAI_RATE_LIMIT",
    "EXTERNAL_MCP_RATE_LIMIT",
    
    # Monitoring
    "HealthChecker",
    "MetricsCollector",
    "HealthStatus",
    "ComponentType",
    "HealthCheckResult",
    "SystemMetrics",
    "health_checker",
    "metrics_collector",
    "setup_default_health_checks",
    "check_whatsapp_api",
    "check_airtable_api",
    "check_database_connection",
    "check_redis_connection",
    
    # Configuration
    "ConfigManager",
    "AppConfig",
    "DatabaseConfig",
    "RedisConfig",
    "WhatsAppConfig",
    "AirtableConfig",
    "SecurityConfig",
    "MonitoringConfig",
    "ServerConfig",
    "Environment",
    "LogLevel",
    "config_manager",
    "get_config",
    "load_config",
    
    # Logging
    "LoggingLevel",
    "StructuredFormatter",
    "ColoredFormatter",
    "LoggerManager",
    "logger_manager",
    "get_logger",
    "configure_logging",
    "log_function_call",
    "log_function_result",
    "log_api_request",
    "log_api_response",
    
    # Validation
    "ValidationError",
    "ValidationSeverity",
    "ValidationResult",
    "Validator",
    "StringValidator",
    "EmailValidator",
    "PhoneValidator",
    "URLValidator",
    "NumberValidator",
    "ListValidator",
    "DictValidator",
    "JSONValidator",
    "DateTimeValidator",
    "validate_email",
    "validate_phone",
    "validate_url",
    "validate_json",
    "sanitize_string",
    "sanitize_phone",
    "validate_whatsapp_number",
    "validate_airtable_record_id",
    "validate_airtable_base_id",
]